"use client";
import { useEffect,useState } from "react";
import { Plus,ShieldCheck,Trash2,Save,LoaderCircle,Info,Check,ExternalLink } from "lucide-react";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { Checkbox } from "@/components/ui/checkbox";
import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { SiteHeader } from "./site-header";
import { SiteFooter } from "./site-footer";
import { DEFAULT_ADS,type AdSettings,type Certificate } from "@/lib/types";

export default function Dashboard(){
 const [certificates,setCertificates]=useState<Certificate[]>([]),[name,setName]=useState(""),[notes,setNotes]=useState(""),[p12,setP12]=useState<File|null>(null),[profile,setProfile]=useState<File|null>(null),[password,setPassword]=useState(""),[confirmed,setConfirmed]=useState(false);
 const [ads,setAds]=useState<AdSettings>(DEFAULT_ADS),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[pending,setPending]=useState<string|null>(null),[formKey,setFormKey]=useState(0);
 async function load(){setLoading(true);setError("");try{const [cr,configr]=await Promise.all([fetch("/api/admin/certificates"),fetch("/api/config")]);const [cb,config]=await Promise.all([cr.json() as Promise<{error?:string;certificates:Certificate[]}>,configr.json() as Promise<{error?:string;ads:AdSettings}>]);if(!cr.ok||!configr.ok)throw new Error(cb.error||config.error);setCertificates(cb.certificates);setAds(config.ads);}catch(e){setError(e instanceof Error?e.message:"Settings couldn’t load. Please retry.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function add(e:React.FormEvent){e.preventDefault();if(!p12||!profile||!confirmed||busy)return;setBusy(true);setError("");setMessage("");try{const {validateCertificate}=await import("@/lib/certificate-validation");const details=await validateCertificate(p12,profile,password);const form=new FormData();form.set("name",name);form.set("notes",notes);form.set("password",password);form.set("p12",p12);form.set("profile",profile);form.set("shareConfirmed","true");form.set("expiresAt",details.expiresAt||"");form.set("teamId",details.teamId);form.set("profileType",details.profileType);
 const r=await fetch("/api/admin/certificates",{method:"POST",body:form});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error);setName("");setNotes("");setPassword("");setP12(null);setProfile(null);setConfirmed(false);setFormKey(k=>k+1);await load();setMessage("Certificate added. It’s now available in the signer. Revocation status is unverified until you test it on an iPhone.");}catch(e){setError(e instanceof Error?e.message:"The certificate couldn’t be saved.");}finally{setBusy(false);}}
 async function update(cert:Certificate,enabled:boolean,status=cert.status){setPending(cert.id);setError("");setMessage("");try{const r=await fetch("/api/admin/certificates/"+cert.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled,status})});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error);setCertificates(items=>items.map(c=>c.id===cert.id?{...c,enabled:enabled?1:0,status}:c));setMessage("Certificate availability saved.");}catch(e){setError(e instanceof Error?e.message:"The change couldn’t be saved.");}finally{setPending(null);}}
 async function remove(cert:Certificate){setPending(cert.id);setError("");setMessage("");try{const r=await fetch("/api/admin/certificates/"+cert.id,{method:"DELETE"});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error);setCertificates(items=>items.filter(c=>c.id!==cert.id));setMessage("Certificate removed.");}catch(e){setError(e instanceof Error?e.message:"The certificate couldn’t be removed.");}finally{setPending(null);}}
 async function saveAds(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/admin/ads",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(ads)});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error);setMessage("Banner settings saved.");}catch(e){setError(e instanceof Error?e.message:"Ad settings couldn’t be saved.");}finally{setBusy(false);}}
 return <><SiteHeader active="manage"/><main className="admin-main"><div className="page-intro"><div><span className="eyebrow">OWNER DASHBOARD</span><h1>Your signer, your controls<span>.</span></h1><p>Add certificates and manage advertising.</p></div><a className="secondary-button" href="/">View signer<ExternalLink size={16}/></a></div><Tabs defaultValue="certificates"><TabsList className="admin-tabs"><TabsTrigger value="certificates">Certificates</TabsTrigger><TabsTrigger value="ads">Advertising</TabsTrigger><TabsTrigger value="launch">Launch guide</TabsTrigger></TabsList>
 {error&&<div className="notice error" role="alert"><Info size={18}/>{error}</div>}{message&&<div className="notice success" role="status"><Check size={18}/>{message}</div>}{loading&&<div className="notice"><LoaderCircle size={18} className="spin"/>Loading your saved settings…</div>}
 <TabsContent value="certificates"><div className="admin-grid"><section className="panel"><h2><Plus size={19}/> Add a shared certificate</h2><p className="panel-subtitle">Add the pair of signing files once. Visitors can select it from the signer immediately.</p><form onSubmit={e=>void add(e)} key={formKey}><fieldset disabled={busy||loading} className="admin-form"><label className="form-label">Certificate name<input required maxLength={120} placeholder="e.g. Amaazbots certificate · October" value={name} onChange={e=>setName(e.target.value)}/></label><label className="form-label">Certificate (.p12)<input type="file" required accept=".p12,.pfx" onChange={e=>setP12(e.target.files?.[0]||null)}/></label><label className="form-label">Provisioning profile (.mobileprovision)<input type="file" required accept=".mobileprovision" onChange={e=>setProfile(e.target.files?.[0]||null)}/></label><label className="form-label">Certificate password<input type="password" autoComplete="off" placeholder="Leave empty if it has no password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="form-label">Note for visitors (optional)<input maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Device eligibility or anything visitors need to know"/></label><label className="checkbox-line"><Checkbox checked={confirmed} onCheckedChange={value=>setConfirmed(value===true)} disabled={busy||loading}/><span>I’m allowed to share these files and their password publicly with visitors.</span></label><div className="notice"><Info size={18}/><span>Shared certificates are downloadable by visitors. Keep your private developer certificate in “My certificate” on the signer instead.</span></div><button className="primary-button" disabled={!confirmed||busy||loading||!p12||!profile||!name.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:<Plus size={18}/>} {busy?"Checking and saving…":"Add certificate"}</button></fieldset></form></section>
 <section className="panel"><h2><ShieldCheck size={20}/> Your certificates <span className="count-badge">{certificates.length}</span></h2>{!loading&&certificates.length===0?<div className="dashboard-empty"><ShieldCheck size={35}/><h3>No certificates added</h3><p>Add a .p12 and its matching provisioning profile to make your first shared certificate available.</p></div>:<div className="admin-certificates">{certificates.map(cert=><article className="admin-certificate" key={cert.id}><div className="cert-row"><div><h3>{cert.name}</h3><p>{cert.profile_type} · {cert.team_id||"Apple team"}</p>{cert.expires_at&&<p>Profile expires {new Date(cert.expires_at).toLocaleDateString()}</p>}</div><Switch aria-label={"Show "+cert.name+" to visitors"} checked={!!cert.enabled} disabled={pending===cert.id||busy} onCheckedChange={enabled=>void update(cert,enabled)}/></div><p className="field-help">{cert.enabled?"Shown to visitors":"Hidden from visitors"}</p><RadioGroup className="status-picker" value={cert.status} onValueChange={status=>void update(cert,!!cert.enabled,status)} disabled={pending===cert.id||busy} aria-label={"Availability of "+cert.name}>{[["unverified","Not verified"],["tested","Tested on iPhone"],["revoked","Revoked"]].map(([value,label])=><label key={value}><RadioGroupItem value={value}/>{label}</label>)}</RadioGroup><AlertDialog><AlertDialogTrigger className="delete-button" disabled={pending===cert.id||busy}><Trash2 size={15}/> Remove certificate</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {cert.name}?</AlertDialogTitle><AlertDialogDescription>This removes the certificate files and hides them from the signer. You can upload the files again later.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep certificate</AlertDialogCancel><AlertDialogAction onClick={()=>void remove(cert)}>Remove certificate</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></article>)}</div>}</section></div></TabsContent>
 <TabsContent value="ads"><div className="admin-grid"><section className="panel"><h2>Advertising settings</h2><p className="panel-subtitle">Manage each banner separately. Enabled banners load automatically.</p><form onSubmit={e=>void saveAds(e)}><fieldset className="admin-form" disabled={busy||loading}>
 <section className="ad-settings-slot"><h3>Sidebar banner · 300 × 250</h3><p className="field-help">Appears beside the signing workspace, or below it on mobile.</p><label className="form-label">Ad provider<input value={ads.provider} maxLength={80} required onChange={e=>setAds({...ads,provider:e.target.value})} placeholder="Adcash"/></label><label className="form-label">Banner embed code<textarea rows={8} className="code-input" value={ads.html} maxLength={50000} onChange={e=>setAds({...ads,html:e.target.value})} placeholder="Paste the library and zone scripts for your 300 × 250 banner"/></label><label className="switch-line"><div><strong>Show sidebar banner</strong><p>Switch off to pause this placement.</p></div><Switch checked={ads.enabled} disabled={busy||loading} onCheckedChange={enabled=>setAds({...ads,enabled})} aria-label="Enable sidebar banner"/></label></section>
 <section className="ad-settings-slot"><h3>Signed-app banner · 300 × 100</h3><p className="field-help">Appears below the result after an IPA is signed.</p><label className="form-label">Ad provider<input value={ads.result.provider} maxLength={80} required onChange={e=>setAds({...ads,result:{...ads.result,provider:e.target.value}})} placeholder="Adcash"/></label><label className="form-label">Banner embed code<textarea rows={8} className="code-input" value={ads.result.html} maxLength={50000} onChange={e=>setAds({...ads,result:{...ads.result,html:e.target.value}})} placeholder="Paste the library and zone scripts for your 300 × 100 banner"/></label><label className="switch-line"><div><strong>Show signed-app banner</strong><p>Switch off to pause this placement.</p></div><Switch checked={ads.result.enabled} disabled={busy||loading} onCheckedChange={enabled=>setAds({...ads,result:{...ads.result,enabled}})} aria-label="Enable signed-app banner"/></label></section>
 <button className="primary-button" disabled={busy||loading}>{busy?<LoaderCircle className="spin" size={18}/>:<Save size={18}/>}Save ad settings</button></fieldset></form></section><section className="panel guide-panel"><span className="eyebrow">ADCASH SETUP</span><h2>Connect your publisher account.</h2><ol><li>Create or log into an Adcash publisher account.</li><li>Add your public website address and complete their verification.</li><li>Create a separate Display zone for each banner size.</li><li>Paste its library and zone scripts into the matching code box and save.</li><li>Check the sidebar banner. Sign an IPA to see the smaller banner below the result.</li></ol><p>Use 300 × 250 for the sidebar and 300 × 100 for the signed-app banner. Each tag runs in its own isolated frame, so include the library script in each code box.</p><p>Adcash decides whether to approve your website and traffic. Test your actual tags before launch.</p><a className="text-link" href="https://support.adcash.com/en/articles/362-publisher-account-setup-and-monetization" target="_blank" rel="noreferrer">Adcash setup instructions</a></section></div></TabsContent>
 <TabsContent value="launch"><section className="panel launch-guide"><h2>Before inviting visitors</h2><ol><li><strong>Add your certificates.</strong><p>Use a .p12 with its private key, matching .mobileprovision, and the password. Test installation on an iPhone, then select “Tested on iPhone.” This label is your report, not an automatic revocation check.</p></li><li><strong>Choose a public address.</strong><p>Your review site starts private. iOS must fetch the manifest and IPA without a ChatGPT login. Ask ChatGPT to make the site public and enable install links together. A custom domain can be connected later.</p></li><li><strong>Check installation.</strong><p>Sign a small IPA you own. Prepare its install link, open it in Safari, and confirm iOS accepts it. Ad Hoc profiles only cover registered devices; App Store and development profiles are not offered as direct installs.</p></li><li><strong>Add your ad code.</strong><p>Use the Advertising tab. Add the public domain in your publisher account and confirm the banner works before enabling it for visitors.</p></li><li><strong>Replace certificates when needed.</strong><p>Pause a certificate, mark it revoked, or remove it, then upload a replacement. Visitors see saved changes without rebuilding the site.</p></li></ol><p>Signing is free for visitors. Uploaded install files use hosting storage and bandwidth; any hosting and ad-network charges depend on your accounts.</p><a className="text-link" href="/help">Read the installation guide</a></section></TabsContent></Tabs>{!loading&&error&&<button className="text-link" onClick={()=>void load()}>Reload saved settings</button>}</main><SiteFooter/></>;
}
