"use client";
import { useEffect, useRef, useState } from "react";
import { Upload, FileArchive, ShieldCheck, KeyRound, LockKeyhole, Smartphone, Zap, Check, X, Info, Download, LoaderCircle, Copy, QrCode } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Checkbox } from "@/components/ui/checkbox";
import { SiteHeader } from "./site-header";
import { SiteFooter } from "./site-footer";
import { AdSlot } from "./ad-slot";
import { DEFAULT_ADS, type AdSettings, type AppMetadata, type Certificate } from "@/lib/types";
import { getMetadata, runSigning } from "@/lib/signing";
import { assertSignedIpa } from "@/lib/signature-check";
import { IPA_MAX_SIZE_BYTES, IPA_MAX_SIZE_MB } from "@/lib/ipa-limits";
import { uploadSignedIpa, type InstallLink, type UploadSlot } from "@/lib/upload-signed-ipa";

type Result = { blob:Blob; url:string; metadata:AppMetadata; };
type Install = InstallLink;
export default function Signer() {
 const [ipa,setIpa]=useState<File|null>(null),[p12,setP12]=useState<File|null>(null),[profile,setProfile]=useState<File|null>(null),[password,setPassword]=useState("");
 const [mode,setMode]=useState("shared"),[certificates,setCertificates]=useState<Certificate[]>([]),[selected,setSelected]=useState("");
 const [matchAppId,setMatchAppId]=useState(true);
 const [ads,setAds]=useState<AdSettings>(DEFAULT_ADS),[error,setError]=useState(""),[configError,setConfigError]=useState(""),[configLoading,setConfigLoading]=useState(true),[publicInstall,setPublicInstall]=useState(false);
 const [busy,setBusy]=useState(false),[logs,setLogs]=useState<string[]>([]),[phase,setPhase]=useState(""),[signProgress,setSignProgress]=useState(0),[result,setResult]=useState<Result|null>(null),[install,setInstall]=useState<Install|null>(null),[uploadBusy,setUploadBusy]=useState(false),[uploadProgress,setUploadProgress]=useState(0),[copied,setCopied]=useState(false);
 const controller=useRef<AbortController|null>(null),resultRef=useRef<Result|null>(null),xhrRef=useRef<XMLHttpRequest|null>(null);
 async function loadConfig(){setConfigLoading(true);setConfigError("");try{const r=await fetch("/api/config");const body=await r.json() as {error?:string;certificates:Certificate[];ads:AdSettings;publicInstall:boolean};if(!r.ok)throw new Error(body.error);setCertificates(body.certificates);setAds(body.ads);setPublicInstall(body.publicInstall);setSelected(previous=>{if(body.certificates.some((c:Certificate)=>c.id===previous&&available(c)))return previous;return body.certificates.find((c:Certificate)=>c.status==="tested"&&available(c))?.id||body.certificates.find(available)?.id||"";});}catch{setConfigError("Shared certificates couldn’t load. Retry or use your own files.");}finally{setConfigLoading(false);}}
 useEffect(()=>{void loadConfig();return()=>{controller.current?.abort();xhrRef.current?.abort();if(resultRef.current)URL.revokeObjectURL(resultRef.current.url);};},[]);
 function clearResult(){if(resultRef.current)URL.revokeObjectURL(resultRef.current.url);resultRef.current=null;setResult(null);setInstall(null);setCopied(false);setError("");setLogs([]);}
 function selectIpa(file?:File){if(!file)return;clearResult();setIpa(null);if(!file.name.toLowerCase().endsWith(".ipa")){setError("Choose an IPA file to continue.");return;}if(!file.size||file.size>IPA_MAX_SIZE_BYTES){setError(`Choose an IPA up to ${IPA_MAX_SIZE_MB} MB.`);return;}setIpa(file);}
 const available=(cert:Certificate)=>cert.status!=="revoked"&&(!cert.expires_at||Date.parse(cert.expires_at)>Date.now());
 const ready=!!ipa&&(mode==="own"?!!p12&&!!profile:!!selected&&certificates.some(c=>c.id===selected&&available(c)));
 async function sign(){if(!ready||busy||!ipa)return;clearResult();setBusy(true);setSignProgress(8);setPhase("Reading IPA…");const abort=new AbortController();controller.current=abort;
  try{let certFile=p12,profileFile=profile,certPassword=password;
   if(mode==="shared"){setSignProgress(18);setPhase("Loading certificate…");const r=await fetch("/api/certificates/"+selected,{signal:abort.signal});const body=await r.json() as {error?:string;p12:string;profile:string;password:string};if(!r.ok)throw new Error(body.error);const decode=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));certFile=new File([decode(body.p12)],"certificate.p12");profileFile=new File([decode(body.profile)],"profile.mobileprovision");certPassword=body.password;}
   if(!certFile||!profileFile)throw new Error("Choose both certificate files.");setSignProgress(32);setPhase("Checking certificate…");const {validateCertificate}=await import("@/lib/certificate-validation");await validateCertificate(certFile,profileFile,certPassword);if(abort.signal.aborted)throw new Error("Signing cancelled.");
   setSignProgress(45);setPhase("Checking app compatibility…");const metadata=await getMetadata(ipa,new Uint8Array(await profileFile.arrayBuffer()),matchAppId);setSignProgress(58);setPhase("Signing app in your browser…");
   const blob=await runSigning(ipa,certFile,profileFile,certPassword,metadata.bundleId,line=>{if(/password/i.test(line))return;setLogs(previous=>[...previous.slice(-79),line]);},abort.signal,metadata.needsBundleCleanup);
   setSignProgress(88);setPhase("Verifying signed IPA…");await assertSignedIpa(blob,metadata.bundleId,metadata.needsBundleCleanup);if(abort.signal.aborted)throw new Error("Signing cancelled.");const newResult={blob,url:URL.createObjectURL(blob),metadata};resultRef.current=newResult;setResult(newResult);setSignProgress(100);setPhase("Your IPA is signed.");
  }catch(e){setError(e instanceof Error?e.message:"Signing couldn’t finish. Check your files and try again.");}finally{setBusy(false);controller.current=null;}
 }
 async function prepareInstall(){if(!result||uploadBusy)return;setError("");setUploadBusy(true);setUploadProgress(0);
  try{if(result.blob.size>IPA_MAX_SIZE_BYTES)throw new Error(`The signed IPA exceeds the ${IPA_MAX_SIZE_MB} MB install-link limit. Download the file instead.`);const r=await fetch("/api/installs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...result.metadata,size:result.blob.size})});const slot=await r.json() as UploadSlot & {error?:string};if(!r.ok)throw new Error(slot.error);
   const uploaded=await uploadSignedIpa(result.blob,slot,setUploadProgress,xhr=>{xhrRef.current=xhr;});setInstall(uploaded);
  }catch(e){setError(e instanceof Error?e.message:"The install link couldn’t be prepared.");}finally{setUploadBusy(false);xhrRef.current=null;}
 }
 async function copyLink(){if(!install)return;try{await navigator.clipboard.writeText(install.pageUrl);setCopied(true);}catch{setError("Copy the installation link shown below and open it in Safari on your iPhone.");}}
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:unknown)=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(ctx.registerTool({name:"list_shared_certificates",title:"List shared certificates",description:"Read the shared IPA signing certificates shown on this page, including availability and profile expiry.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("This tool takes an empty object.");return{certificates:certificates.map(c=>({id:c.id,name:c.name,status:c.status,profileExpiry:c.expires_at,available:available(c)}))};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[certificates]);
 return <><SiteHeader/><main className="signer-main"><div className="page-intro"><div><span className="eyebrow"><Zap size={14}/> ONLINE IPA SIGNER</span><h1>Sign your IPA<span>.</span></h1><p>Choose your app. Pick a certificate. Make it yours.</p></div><div className="local-badge"><LockKeyhole size={18}/><span>Signed in your browser<small>Your private certificate stays on your device.</small></span></div></div><div className="workspace-grid"><div className="signing-column"><section className="signing-card"><div className="card-top"><span className="card-title">Signing workspace</span><span className="small-label">.IPA → iPHONE</span></div>
 <fieldset disabled={busy||uploadBusy} className="signing-fieldset"><div className="step-title"><span className="step-number">01</span><div><h2>Your IPA file</h2><p>The app you want to install.</p></div></div><label className={"dropzone "+(ipa?"has-file":"")} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&!uploadBusy)selectIpa(e.dataTransfer.files[0]);}}><input className="file-overlay" type="file" accept=".ipa" aria-label="Choose IPA file" onChange={e=>selectIpa(e.target.files?.[0])}/><div className="upload-icon">{ipa?<FileArchive size={29}/>:<Upload size={27}/>}</div><strong>{ipa?.name||"Drop your IPA here"}</strong><span>{ipa?(ipa.size/1024/1024).toFixed(1)+" MB · Tap to choose another file":"or browse files on your device"}</span><small>IPA files up to {IPA_MAX_SIZE_MB} MB</small></label>
 <div className="step-title certificate-step"><span className="step-number">02</span><div><h2>Signing certificate</h2><p>Use a shared certificate or bring your own.</p></div></div><Tabs value={mode} onValueChange={value=>{if(!busy&&!uploadBusy){clearResult();setMode(value);}}}><TabsList className="certificate-tabs"><TabsTrigger value="shared" disabled={busy||uploadBusy}><ShieldCheck size={16}/> Shared certificates</TabsTrigger><TabsTrigger value="own" disabled={busy||uploadBusy}><KeyRound size={16}/> My certificate</TabsTrigger></TabsList><TabsContent value="shared">
 {configLoading?<div className="certificate-empty"><LoaderCircle className="spin" size={20}/><p>Loading certificates…</p></div>:configError?<div className="certificate-empty"><div><p>{configError}</p><button className="text-link" onClick={()=>void loadConfig()}>Retry</button></div></div>:certificates.length===0?<div className="certificate-empty"><ShieldCheck size={24}/><div><strong>No shared certificates yet</strong><p>The owner hasn’t added certificate files yet. You can sign with your own files.</p><button className="text-link" onClick={()=>setMode("own")}>Use my certificate</button></div></div>:<RadioGroup value={selected} onValueChange={value=>{clearResult();setSelected(value);}} className="certificate-list" aria-label="Shared signing certificate">{certificates.map(cert=>{const expired=!!cert.expires_at&&Date.parse(cert.expires_at)<=Date.now();const label=expired?"Expired":cert.status==="revoked"?"Revoked":cert.status==="tested"?"Working":"Untested";return <label key={cert.id} className={"certificate-option "+(selected===cert.id?"selected ":"")+(!available(cert)?"unavailable ":"")+"status-"+label.toLowerCase()}><RadioGroupItem value={cert.id} disabled={!available(cert)} aria-label={cert.name}/><span><strong>{cert.name}{selected===cert.id&&available(cert)&&<small className="recommended-label">Recommended</small>}</strong><small>{cert.notes||({enterprise:"Enterprise profile",adhoc:"Ad Hoc · registered devices only",development:"Development · use a desktop sideloader",appstore:"App Store profile · direct install unavailable"}[cert.profile_type]||"Provisioning profile")}</small>{cert.expires_at&&<small>Profile expires {new Date(cert.expires_at).toLocaleDateString()}</small>}</span><em>{label}</em></label>;})}</RadioGroup>}
 </TabsContent><TabsContent value="own"><div className="certificate-inputs"><label>Certificate (.p12)<input type="file" accept=".p12,.pfx" onChange={e=>{clearResult();setP12(e.target.files?.[0]||null);}}/></label><label>Provisioning profile<input type="file" accept=".mobileprovision" onChange={e=>{clearResult();setProfile(e.target.files?.[0]||null);}}/></label><label className="full-width">Certificate password<input type="password" autoComplete="off" value={password} onChange={e=>{clearResult();setPassword(e.target.value);}} placeholder="Enter the .p12 password"/></label></div><p className="field-help">These files stay on your device. An empty password is fine if your .p12 has no password.</p></TabsContent></Tabs><div className="bundle-id-option"><div className="checkbox-line"><Checkbox id="match-app-id" checked={matchAppId} disabled={busy||uploadBusy} aria-describedby="match-app-id-help" onCheckedChange={value=>{clearResult();setMatchAppId(value===true);}}/><label htmlFor="match-app-id">Match app ID to profile (recommended)</label></div><p className="field-help" id="match-app-id-help">Keep this enabled for shared certificates and Delta. It lets the signed copy use the ID permitted by the profile. Apps using the same ID replace each other, and changing the ID may affect sign-in or other app features.</p></div></fieldset>
 <div className="sign-action"><button className="primary-button" disabled={!ready||busy||uploadBusy} onClick={()=>void sign()}>{busy?<LoaderCircle size={19} className="spin"/>:<ShieldCheck size={19}/>} {busy?phase:result?"Sign again":"Sign IPA"}</button><p><LockKeyhole size={13}/> No Apple Account required</p></div>
 {busy&&<div className="sign-progress" role="status" aria-live="polite"><div><strong>{phase}</strong><span>{signProgress}%</span></div><div className="progress-track"><span style={{width:signProgress+"%"}}/></div><p>Keep this page open. Large IPAs can take a few minutes.</p><button className="text-link" onClick={()=>controller.current?.abort()}>Cancel signing</button></div>}{logs.length>0&&<details className="signing-logs"><summary>Signing details</summary><pre>{logs.join("\n")}</pre></details>}
 {result&&<div className="result-card"><div className="result-title"><span><Check size={22}/></span><div><h3>Your IPA is signed.</h3><p>{result.metadata.title} · {(result.blob.size/1024/1024).toFixed(1)} MB</p></div></div><p className="bundle-id-details">Signed app ID: <code>{result.metadata.bundleId}</code>{result.metadata.originalBundleId&&<><br/>Changed from <code>{result.metadata.originalBundleId}</code> to match this profile.</>}</p>{result.metadata.needsBundleCleanup&&<p className="field-help">Compatibility mode removed embedded extensions or Watch components so the main app could use one profile. Delta’s main app can still install, but companion features from those components are not included.</p>}<div className="result-actions"><a className="secondary-button" href={result.url} download={(ipa?.name.replace(/\.ipa$/i,"")||"app")+"_signed.ipa"}><Download size={17}/> Download IPA</a>{install?<a className="primary-button" href={install.installUrl}><Smartphone size={17}/> Install on iPhone</a>:<button className="primary-button" onClick={()=>void prepareInstall()} disabled={!publicInstall||uploadBusy||!["enterprise","adhoc"].includes(result.metadata.profileType)}>{uploadBusy?<LoaderCircle className="spin" size={17}/>:<Smartphone size={17}/>} {uploadBusy?"Uploading · "+uploadProgress+"%":"Prepare install link"}</button>}</div>{!publicInstall?<p className="field-help">This is a private preview. Download signing works here; direct installation becomes available when the owner makes the site public.</p>:!["enterprise","adhoc"].includes(result.metadata.profileType)?<p className="field-help">This profile needs a desktop sideloader. Direct installation requires an Enterprise or compatible Ad Hoc profile.</p>:<p className="field-help">Preparing an install link uploads only the signed IPA. The link expires after 24 hours. iOS still checks your certificate and device eligibility.</p>}{install&&<div className="install-share"><div className="install-link"><label>Open this link in Safari on your iPhone<input value={install.pageUrl} readOnly aria-label="Installation page URL"/></label><button className="secondary-button" onClick={()=>void copyLink()}><Copy size={16}/>{copied?"Copied":"Copy link"}</button></div><div className="qr-card"><img src={"https://quickchart.io/qr?size=180&margin=1&text="+encodeURIComponent(install.pageUrl)} alt="QR code for this installation page" width="180" height="180"/><p><QrCode size={16}/> Scan with your iPhone camera</p></div></div>}</div>}
 {error&&<div role="alert" className="notice error"><X size={18}/>{error}</div>}</section>{result&&<AdSlot settings={ads.result} slot="result"/>}</div><aside className="workspace-aside"><div className="info-card"><span className="eyebrow">THREE STEPS. ONE APP.</span><h2>From file to<br/>Home Screen.</h2><ol className="flow-list"><li><span><Upload size={19}/></span><div><strong>Choose your IPA</strong><p>Select a compatible app from Files.</p></div></li><li><span><ShieldCheck size={19}/></span><div><strong>Sign the app</strong><p>Your browser applies the certificate.</p></div></li><li><span><Smartphone size={19}/></span><div><strong>Install on iPhone</strong><p>Prepare a link, then open it in Safari.</p></div></li></ol><a href="/help" className="text-link">Need help installing?</a></div><div className="certificate-note"><Info size={20}/><div><strong>Certificate matters.</strong><p>A successful signature doesn’t guarantee installation. Your certificate and profile must be valid for your device.</p></div></div><AdSlot settings={ads}/></aside></div><div className="bottom-note"><Check size={17}/><p>Personal certificates and original IPAs stay in your browser. Only a signed IPA is uploaded when you prepare an installation link.</p></div></main><SiteFooter/></>;
}
