import { unzipSync } from "fflate";
import { readPlist } from "./plist";
import { appIdentifierForBundleId, inspectProfile } from "./profile";
import { IPA_MAX_ENTRY_BYTES } from "./ipa-limits";
export async function assertSignedIpa(blob:Blob,expectedBundleId?:string,expectBundleCleanup=false){
 const bytes=new Uint8Array(await blob.arrayBuffer());let root="";
 const infoFiles=unzipSync(bytes,{filter:entry=>/^Payload\/[^/]+\.app\/Info\.plist$/.test(entry.name)&&entry.originalSize<=2*1024*1024});const names=Object.keys(infoFiles);
 if(names.length!==1)throw new Error("The signing engine returned an invalid app archive.");root=names[0].slice(0,-10);const info=readPlist(infoFiles[names[0]]);const executable=String(info.CFBundleExecutable||"");if(!executable||executable.includes("/")||executable.includes("\\"))throw new Error("The app executable couldn’t be checked.");
 if(expectBundleCleanup){const leftovers=Object.keys(unzipSync(bytes,{filter:entry=>/\.(?:appex|app)\/Info\.plist$/i.test(entry.name.replace(/^Payload\/[^/]+\.app\//,""))&&entry.originalSize<=2*1024*1024}));if(leftovers.length)throw new Error("The compatibility cleanup did not remove every embedded extension or Watch app.");}
 const bundleId=String(info.CFBundleIdentifier||"");if(expectedBundleId!==undefined&&bundleId!==expectedBundleId)throw new Error("The signing engine didn’t apply the selected app ID. Try signing again.");
 const executablePath=root+executable,profilePath=root+"embedded.mobileprovision";const files=unzipSync(bytes,{filter:entry=>(entry.name===executablePath&&entry.originalSize<=IPA_MAX_ENTRY_BYTES)||(entry.name===profilePath&&entry.originalSize<=1024*1024)});const data=files[executablePath];if(!data)throw new Error("The signed app is missing its executable.");
 const profile=files[profilePath];if(!profile)throw new Error("The signed app is missing its provisioning profile.");const expectedAppIdentifier=appIdentifierForBundleId(inspectProfile(profile),bundleId);
 function verifyThin(b:Uint8Array){const v=new DataView(b.buffer,b.byteOffset,b.byteLength);if(b.length<32)throw new Error("The app executable is damaged.");const magic=v.getUint32(0,false),little=magic===0xcffaedfe||magic===0xcefaedfe;const is64=magic===0xcffaedfe||magic===0xfeedfacf;if(![0xcffaedfe,0xcefaedfe,0xfeedfacf,0xfeedface].includes(magic))throw new Error("The app executable format isn’t supported.");let pos=is64?32:28,signatureOffset=0,signatureSize=0;const count=v.getUint32(16,little);if(count>10000)throw new Error("The app executable is damaged.");
  for(let i=0;i<count;i++){if(pos+8>b.length)throw new Error("The app load commands are damaged.");const cmd=v.getUint32(pos,little),size=v.getUint32(pos+4,little);if(size<8||pos+size>b.length)throw new Error("The app load commands are damaged.");if(cmd===0x1d&&size>=16){signatureOffset=v.getUint32(pos+8,little);signatureSize=v.getUint32(pos+12,little);}if((cmd===0x21||cmd===0x2c)&&size>=20&&v.getUint32(pos+16,little)!==0)throw new Error("This app is encrypted. Use a compatible IPA you own; this signer cannot decrypt apps.");pos+=size;}
  if(!signatureOffset||signatureSize<12||signatureOffset+signatureSize>b.length)throw new Error("No complete app signature was produced. Try a different certificate.");const s=new DataView(b.buffer,b.byteOffset+signatureOffset,signatureSize);if(s.getUint32(0)!==0xfade0cc0)throw new Error("The app signature is invalid.");const slots=s.getUint32(8);if(slots>100||12+slots*8>signatureSize)throw new Error("The app signature is damaged.");let cms=false;
  let matchingAppId=false;for(let i=0;i<slots;i++){const type=s.getUint32(12+i*8),offset=s.getUint32(16+i*8);if(offset+8>=signatureSize)continue;const size=s.getUint32(offset+4);if(type===0x10000){cms=s.getUint32(offset)===0xfade0b01&&size>8&&offset+size<=signatureSize;}if(type===5&&size>8&&offset+size<=signatureSize){const entitlements=readPlist(b.subarray(signatureOffset+offset+8,signatureOffset+offset+size));const appId=String(entitlements["application-identifier"]||"");matchingAppId=appId===expectedAppIdentifier;}}
  if(!cms)throw new Error("A certificate signature wasn’t produced. Check that the .p12 includes the full Apple certificate chain.");
  if(!matchingAppId)throw new Error("The signing profile didn’t produce the app’s required identifier. Choose a different profile.");
 }
 const view=new DataView(data.buffer,data.byteOffset,data.byteLength),magic=view.getUint32(0);if(magic===0xcafebabe||magic===0xbebafeca){const little=magic===0xbebafeca,count=view.getUint32(4,little);if(count<1||count>20)throw new Error("The universal executable is damaged.");for(let i=0;i<count;i++){const p=8+i*20;if(p+20>data.length)throw new Error("The universal executable is damaged.");const offset=view.getUint32(p+8,little),size=view.getUint32(p+12,little);if(offset+size>data.length)throw new Error("The universal executable is damaged.");verifyThin(data.subarray(offset,offset+size));}}else verifyThin(data);
}
