import { database } from "@/lib/server";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { headers } from "next/headers";
import { Smartphone,Download,ShieldCheck } from "lucide-react";
import { InstallCountdown } from "@/components/install-countdown";
export const dynamic="force-dynamic";
export default async function Install({params}:{params:Promise<{id:string}>}){const {id}=await params;const row=await database().prepare("SELECT title,bundle_id,version,size,expires_at FROM installs WHERE id=? AND ready=1").bind(id).first<{title:string;bundle_id:string;version:string;size:number;expires_at:number}>();if(!row||row.expires_at<Date.now())return <><SiteHeader/><main className="document-main"><h1>Installation link unavailable</h1><p>This link has expired or doesn’t exist. Prepare a new link from the signer.</p><a href="/" className="text-link">Open the signer</a></main><SiteFooter/></>;
const requestHeaders=await headers();const host=requestHeaders.get("host");const protocol=requestHeaders.get("x-forwarded-proto")||"https";if(!host)return null;const origin=protocol+"://"+host;const pageUrl=origin+"/install/"+id;const manifestUrl=pageUrl+"/manifest.plist";return <><SiteHeader/><main className="document-main"><section className="panel install-panel"><div className="install-icon"><ShieldCheck size={42}/></div><span className="eyebrow">SIGNED WITH AMAAZSIGN</span><h1>{row.title}</h1><div className="install-meta"><span>Version {row.version}</span><span>{(row.size/1024/1024).toFixed(1)} MB</span><InstallCountdown expiresAt={row.expires_at}/></div><code className="install-bundle">{row.bundle_id}</code><p>Open this page in Safari on your iPhone or iPad. iOS will still verify the certificate and your device eligibility.</p><div className="install-page-grid"><div><div className="result-actions"><a className="primary-button" href={"itms-services://?action=download-manifest&url="+encodeURIComponent(manifestUrl)}><Smartphone size={18}/>Install on iPhone</a><a className="secondary-button" href={"/install/"+id+"/app.ipa"}><Download size={18}/>Download IPA</a></div><ol className="mini-install-steps"><li>Open this page in Safari.</li><li>Tap Install on iPhone and confirm.</li><li>If requested, trust the enterprise developer in Settings.</li></ol></div><div className="qr-card"><img src={"https://quickchart.io/qr?size=200&margin=1&text="+encodeURIComponent(pageUrl)} alt="QR code for this installation page" width="200" height="200"/><p>Scan to open on iPhone</p></div></div><p className="field-help">Available until {new Date(row.expires_at).toLocaleString("en",{timeZone:"UTC"})} UTC.</p><a href="/help" className="text-link">Installation help</a></section></main><SiteFooter/></>;}
